# Generated by Django 6.0 on 2025-12-16 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('porteur de projet', 'Porteur de Projet'), ('investisseur', 'Invetisseur'), ('administrateur', 'Administrateur')], default='porteur de projet', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('proposé', 'Proposé'), ('validé', 'Validé'), ('financé', 'Financé')], default='Propose', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interlocalapp.categorie')),
                ('porteur', models.ForeignKey(limit_choices_to={'role': 'Porteur de projet'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='interlocalapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_investissement', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='interlocalapp.projet')),
                ('investisseur', models.ForeignKey(limit_choices_to={'role': 'Investisseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='interlocalapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'Administrateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interlocalapp.utilisateur')),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interlocalapp.projet')),
            ],
        ),
    ]
