# Generated by Django 6.0 on 2026-05-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='investisseur',
            field=models.ForeignKey(limit_choices_to={'role': 'investisseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='interlocalapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='porteur',
            field=models.ForeignKey(limit_choices_to={'role': 'porteur de projet'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='interlocalapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('propose', 'Proposé'), ('validé', 'Validé'), ('financé', 'Financé')], default='propose', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('porteur de projet', 'Porteur de Projet'), ('investisseur', 'Investisseur'), ('administrateur', 'Administrateur')], default='porteur de projet', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationprojet',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'administrateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interlocalapp.utilisateur'),
        ),
    ]
